name: Build Release
on:
  push:
    branches: [master]
  
jobs:
  build-soljson:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout External Repository
        uses: actions/checkout@v3
        with:
          repository: shinkee635/solidity76
          ref: master
          path: solidity76
      
      - name: Build soljson
        env:
          GITHUB_WORKSPACE: ${{ env.GITHUB_WORKSPACE }}/solidity76
        run: |
          cd solidity76
          chmod +x scripts/ci/docker_build.sh
          cp scripts/docker/buildpack-deps/emscripten.jam ./
          scripts/ci/docker_build.sh buildpack-deps emscripten solbuildpackpusher/solidity-buildpack-deps ems
          scripts/build_emscripten.sh

      - name: Upload Artifact 
        uses: actions/upload-artifact@v4
        with:
          name: soljson
          path: /home/runner/remix-project/remix-project/solidity76/upload/soljson.js


  build-ethereumjs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Checkout ethereumjs-monorepo
        uses: actions/checkout@v3
        with:
          repository: shinkee635/ethereumjs-monorepo
          ref: util32
          path: ethereumjs-monorepo
      
      - name: Build ethereumjs-monorepo
        run: |
          cd ethereumjs-monorepo
          npm i
          cd .. && tar -cjf ethereumjs.tar.bz2 ethereumjs-monorepo

      - uses: actions/upload-artifact@v4
        with:
          name: ethereumjs
          path: ethereumjs.tar.bz2
  
  build-web3:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Checkout web3.js
        uses: actions/checkout@v3
        with:
          repository: shinkee635/web3.js
          ref: v4.3address32
          path: web3.js

      - name: Build web3.js
        run: |
          cd web3.js
          yarn install --ignore-scripts
          yarn build
          cd .. && tar -cjf web3js.tar.bz2 web3.js

      - uses: actions/upload-artifact@v4
        with:
          name: web3js
          path: web3js.tar.bz2
    
  build-remix:
    runs-on: ubuntu-latest
        
    needs: [build-soljson, build-ethereumjs, build-web3]

    steps:
      - uses: actions/checkout@v4
      
      - name: Download soljson artifact
        uses: actions/download-artifact@v4
        with:
          name: soljson

      - name: Download ethereumjs artifact
        uses: actions/download-artifact@v4
        with:
          name: ethereumjs

      - name: Download web3 artifact
        uses: actions/download-artifact@v4
        with:
          name: web3js

      - name: Extract artifacts
        run: |
          tar -xjf ethereumjs.tar.bz2
          tar -xjf web3js.tar.bz2

      - name: Build Remix
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: yarn
        
      - run: |
          yarn install && yarn build
          cd ..
          tar -cjf remix-release.tar.bz2 remix-project

      - name: Upload final artifact
        uses: actions/upload-artifact@v4
        with:
          name: remix-release
          path: /home/runner/work/remix-project/remix-release.tar.bz2
