name: Rebase Pull Requests
on:
  push:
#    branches: [master]
    branches: [disabled]
  workflow_dispatch:
  
jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
      - uses: yann300/rebase-pull-requests@master
